In [58]:
import numpy as np
import scipy.special as sigmoid # funcion sigmoide para evaluacion

## creamos esqueleto(clase) de la red neuronal

In [137]:
class NeuralNetwork:
    
    #initialize the neural network
    def __init__(self, inputnodes,hiddennodes,outputnodes,learningrate):
        self.inputnodes = inputnodes
        self.hiddennodes = hiddennodes
        self.outputnodes = outputnodes
        self.learningrate = learningrate       
        #pesos input-hidden
        self.wih = np.random.normal(0.0, 
                                    pow(self.inputnodes, -0.5),
                                    (self.hiddennodes,self.inputnodes))
        # pesos hidden-output
        self.who = np.random.normal(0.0, 
                                    pow(self.hiddennodes, -0.5),
                                    (self.outputnodes,self.hiddennodes))
        self.activation_function = lambda x: sigmoid.expit(x)
        pass
    
    # query the neural network
    def query(self, inputs_list):
        inputs = np.array(inputs_list, ndmin=2).T
        
        hidden_inputs = np.dot(self.wih, inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        
        final_inputs = np.dot(self.who, hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        
        return final_outputs
    # train the neural network
    def train(self, inputs_list, targets_list):
        inputs = np.array(inputs_list, ndmin=2).T
        targets = np.array(targets_list, ndmin=2).T
        
        hidden_inputs = np.dot(self.wih, inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        
        final_inputs = np.dot(self.who, hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        
        output_errors = targets - final_outputs
        hidden_errors = np.dot(self.who.T, output_errors)
        
        self.who += self.learningrate*np.dot((output_errors*final_outputs*(1.0-final_outputs)),np.transpose(hidden_outputs))
        self.wih += self.learningrate*np.dot((hidden_errors*hidden_outputs*(1.0-hidden_outputs)),np.transpose(inputs))
        
        pass

## inicializamos los nodos de la red

In [138]:
inputnodes = 3
hiddennodes = 5
outputnodes = 1

learningrate = 0.3 # cuanto vamos avanzar

n = NeuralNetwork(inputnodes, hiddennodes,outputnodes,learningrate)

In [139]:
np.random.seed(123)
input_nodes = np.random.rand(3,3)
input_nodes

array([[ 0.69646919,  0.28613933,  0.22685145],
       [ 0.55131477,  0.71946897,  0.42310646],
       [ 0.9807642 ,  0.68482974,  0.4809319 ]])

In [140]:
np.random.seed(100)
output_nodes = np.random.rand(3,1)
output_nodes

array([[ 0.54340494],
       [ 0.27836939],
       [ 0.42451759]])

In [141]:
n.train(input_nodes, output_nodes)

In [147]:
inputnodes = 5
hiddennodes = 5
outputnodes = 2

learningrate = 0.3 # cuanto vamos avanzar

n = NeuralNetwork(inputnodes, hiddennodes,outputnodes,learningrate)

In [148]:
np.random.seed(123)
input_nodes = np.random.rand(3,5)
input_nodes

array([[ 0.69646919,  0.28613933,  0.22685145,  0.55131477,  0.71946897],
       [ 0.42310646,  0.9807642 ,  0.68482974,  0.4809319 ,  0.39211752],
       [ 0.34317802,  0.72904971,  0.43857224,  0.0596779 ,  0.39804426]])

In [149]:
np.random.seed(100)
output_nodes = np.random.rand(3,1)
output_nodes

array([[ 0.54340494],
       [ 0.27836939],
       [ 0.42451759]])

In [150]:
n.train(input_nodes, output_nodes)

In [151]:
n.query(input_nodes)

array([[ 0.71435492,  0.70421598,  0.72566052],
       [ 0.33658369,  0.36323093,  0.35144396]])

In [160]:
inputnodes = 10
hiddennodes = 5
outputnodes = 1

learningrate = 0.3 # cuanto vamos avanzar

n = NeuralNetwork(inputnodes, hiddennodes,outputnodes,learningrate)

In [161]:
np.random.seed(123)
input_nodes = np.random.rand(5,10)
input_nodes

array([[ 0.69646919,  0.28613933,  0.22685145,  0.55131477,  0.71946897,
         0.42310646,  0.9807642 ,  0.68482974,  0.4809319 ,  0.39211752],
       [ 0.34317802,  0.72904971,  0.43857224,  0.0596779 ,  0.39804426,
         0.73799541,  0.18249173,  0.17545176,  0.53155137,  0.53182759],
       [ 0.63440096,  0.84943179,  0.72445532,  0.61102351,  0.72244338,
         0.32295891,  0.36178866,  0.22826323,  0.29371405,  0.63097612],
       [ 0.09210494,  0.43370117,  0.43086276,  0.4936851 ,  0.42583029,
         0.31226122,  0.42635131,  0.89338916,  0.94416002,  0.50183668],
       [ 0.62395295,  0.1156184 ,  0.31728548,  0.41482621,  0.86630916,
         0.25045537,  0.48303426,  0.98555979,  0.51948512,  0.61289453]])

In [162]:
np.random.seed(100)
output_nodes = np.random.rand(5,1)
output_nodes

array([[ 0.54340494],
       [ 0.27836939],
       [ 0.42451759],
       [ 0.84477613],
       [ 0.00471886]])

In [163]:
n.train(input_nodes, output_nodes)

In [165]:
test_nodes = np.random.rand(1,10)
n.query(test_nodes)

array([[ 0.30741797]])